name: Build and Push Images to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-2
      IMAGE_TAG: v1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::279715467865:role/github-ecr-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      ##############################
      # Backend
      ##############################

      - name: Build Backend Image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/photo-gallery-backend:${{ env.IMAGE_TAG }} \
            ./backend

      - name: Push Backend Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/photo-gallery-backend:${{ env.IMAGE_TAG }}

      ##############################
      # Frontend
      ##############################

      - name: Build Frontend Image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/photo-gallery-frontend:${{ env.IMAGE_TAG }} \
            ./frontend

      - name: Push Frontend Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/photo-gallery-frontend:${{ env.IMAGE_TAG }}

      ##############################
      # Cleanup
      ##############################

      - name: Cleanup ECR Images on Failure
        if: failure()
        run: |
          aws ecr batch-delete-image \
            --repository-name photo-gallery-backend \
            --image-ids imageTag=${{ env.IMAGE_TAG }} || true

          aws ecr batch-delete-image \
            --repository-name photo-gallery-frontend \
            --image-ids imageTag=${{ env.IMAGE_TAG }} || true