jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::279715467865:role/github-ecr-oidc-role
          aws-region: ap-south-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Images
      - name: Build Backend Image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/photo-gallery-backend:v1 ./backend

      - name: Build Frontend Image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/photo-gallery-frontend:v1 ./frontend

      # Push Images
      - name: Push Backend Image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/photo-gallery-backend:v2

      - name: Push Frontend Image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/photo-gallery-frontend:v2

      # Cleanup if anything failed
      - name: Cleanup ECR Images
        if: failure()
        run: |
          aws ecr batch-delete-image \
            --repository-name photo-gallery-backend \
            --image-ids imageTag=v1 || true

          aws ecr batch-delete-image \
            --repository-name photo-gallery-frontend \
            --image-ids imageTag=v1 || true